-- Sistema de Gerenciamento Hospitalar da Mentorama
-- Criação das tabelas e constraints

CREATE TABLE medicos (
	matricula int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(200),
	cargo varchar(200),
	departamento varchar(200),
	telefone varchar(11)
);

CREATE TABLE pacientes (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(200),
	telefone varchar(11),
	data_nascimento date
);

CREATE TABLE historico_internacoes (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	id_paciente int,
	entrada_paciente timestamp,
	saida_paciente timestamp,
	diagnostico varchar(1000),
	matricula_medico int,
	CONSTRAINT fk_paciente
		FOREIGN KEY (id_paciente)
		REFERENCES pacientes(id),
	CONSTRAINT fk_medico
		FOREIGN KEY (matricula_medico)
		REFERENCES medicos(matricula)
);